---
title: "Reproducibility Seminar"  
author: 
  - "Wesley S. Burr (Trent)"
  - "`r Sys.Date()`"
date: '*https://bit.ly/Repro_Seminar_2022*'
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: xaringan-themer.css
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      slideNumberFormat: '%current%'
      titleSlideClass: [top, left]
      ratio: '16:9'
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(message = FALSE, 
                      echo = FALSE, 
                      warning = FALSE,
                      fig.align = "center")
```

```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
style_duo_accent(
  primary_color = "#9F999C",
  secondary_color = "#FFE5F3",
  inverse_header_color = "#8F8C8E",
  link_color = "deeppink",
  title_slide_text_color = "#3d3d3d",
  title_slide_background_image = "img/title-slide-background-light.png",
  title_slide_background_position = "left",
  header_font_google = google_font("Josefin Sans"),
  text_font_google   = google_font("Montserrat", "300", "300i"),
  code_font_google   = google_font("Fira Mono")
)
```

class: center, middle

> *You mostly collaborate with yourself, 
> and me-from-two-months-ago never responds to email.*
> 
> --Mark T. Holder

---

class: left, middle

## Links to Slide Sub-Decks

* 01 - [What is Reproducibility?](01-what-is-reproducibility.html)
* 02 - [Importance of Reproducible Coding Habits](02-importance-of-reproducible-coding-habits.html)
* 03 - [Version Control Concepts](03-version-control.html)

---

